// File: app/layout.tsx

import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import Footer from "@/components/footer/Footer";
import Breadcrumb from "@/components/Breadcrumb";
import MainHeader from "@/components/MainHeader";
import PageTransition from "./pageTransition";

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider dynamic>
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}
          <main className="min-h-screen font-sans flex flex-col justify-between relative pt-14 bg-gray-100">
            <MainHeader />
            <Breadcrumb />
            <div className="flex-grow">
              <PageTransition>{children}</PageTransition>
            </div>
            <Footer />
          </main>
          <SanityLive />
        </ClerkProvider>
      </body>
    </html>
  );
}
