// File: app/layout.tsx

import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider dynamic>
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}
          <main className="mt-1 bg-gray-100">
            <Header />
            {children}
            <Footer />
          </main>
          <SanityLive />
        </ClerkProvider>
      </body>
    </html>
  );
}
